name: Terraform Destroy (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to confirm destroy"
        required: true
        default: "NO"

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.confirm == 'YES' }}

    env:
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
      TF_VAR_alb_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan Destroy
        working-directory: infra
        run: terraform plan -destroy -var-file=envs/dev.tfvars -out=tfplan

      - name: Terraform Destroy
        working-directory: infra
        run: terraform apply -auto-approve tfplan

      - name: Destroy Completed
        run: echo "Terraform destroy completed successfully."
