name: Destroy Infrastructure

on:
  workflow_dispatch:   # ‚Üê Manual trigger only

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC
      contents: read

    steps:
      # Checkout infra repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Authenticate to AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize Terraform
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      # Show destroy plan (Safety)
      - name: Terraform Destroy Plan
        working-directory: infra
        run: terraform plan -destroy -var-file=envs/dev.tfvars -out=tfdestroy

      # Destroy infra
      - name: Terraform Destroy Apply
        working-directory: infra
        run: terraform apply -auto-approve tfdestroy
